# 1.1 넘파이
- 넘파이 : 분석자료를 생성, 편집, 가공, 연산을 위한 라이브러리
- 넘파이는 주로 함수의 기능을 하기 때문에 "np.함수()"의 형태로 사용
- cf) 판다스는 주로 클래스의 기능을 하기 때문에 "객체.함수()"의 형태로 주료 사용

In [12]:
import numpy as np

In [2]:
np.array([1,5,6,7])

array([1, 5, 6, 7])

In [12]:
np.array([1.25,5,6,7])
### 넘파이는 하나의 통일된 자료타입을 사용

array([1.25, 5.  , 6.  , 7.  ])

In [13]:
### 0으로 구성된 1차원 자료

np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [14]:
### 1로 구성된 2 by 3 (2차원) 자료

np.ones([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
### 등차수열

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
### graph의 축의 값을 정의 할 때 유용하게 쓰임

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
### 특정 분포를 따르는 확률변수의 값을 생성할 때

np.random.seed(12)

In [11]:
### Uniform(0,1)으로부터 3 by 3 행렬을 생성할 때

np.random.random((3,3))

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [58]:
### 평균이 0이고 분산이 1인 정규분포로부터 3 by 3 행렬을 생성할 때

np.random.normal(0, 1, (3,3))

array([[-0.59703923,  0.56050858,  1.05531088],
       [-0.58374243, -0.60474191,  1.49292058],
       [ 0.61501214,  0.48269056, -0.69363977]])

In [33]:
### 0 to 9 범위의 int로부터 3 by 3 행렬을 생성할 때
np.random.randint(0, 10, (3,3))

array([[9, 9, 7],
       [6, 9, 1],
       [0, 1, 8]])

In [21]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\yeswo\\.conda\\envs\\ttn\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\yeswo\.conda\envs\ttn\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entr

In [34]:
### 객체화

rg = np.random.RandomState(40)
print(rg)

RandomState(MT19937)


In [10]:
np.random.seed(1)
x = np.random.randint(10, size=(2,3,4))

print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24


In [39]:
### array slicing(편집)

x1 = np.arange(9).reshape((3,3))
x = x1 + 1
print(x)
print()
print(x[:2, :2])
print()
x[0,0] = 99
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## 1.1.1 차원변경, 분할, 병합

In [41]:
### 차원변경

x1 = np.arange(3)
x = x1 + 1
print(x)
print(x.reshape(1,3)) # 2차원 행벡터로 변경
print(x[np.newaxis, :]) # 2차원 행벡터로 변경하는 또다른 표현
print(x[:, np.newaxis]) # 2차원 열벡터로 변경

[1 2 3]
[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [46]:
x = np.random.randint(10, size=(100,3,4))
print(x.shape[0])
print(x.shape[1])
print(x.shape[2])

100
3
4


In [68]:
x1 = x.reshape((100, 12))
x2 = x.reshape((-1,12))

print(x1, x1.shape)
print(x2, x2.shape)

### x1과 x2는 동일

[[6 9 4 ... 1 0 6]
 [0 7 9 ... 0 2 7]
 [6 0 1 ... 8 8 8]
 ...
 [6 1 1 ... 8 7 5]
 [0 7 8 ... 8 7 0]
 [8 1 3 ... 9 2 7]] (100, 12)
[[6 9 4 ... 1 0 6]
 [0 7 9 ... 0 2 7]
 [6 0 1 ... 8 8 8]
 ...
 [6 1 1 ... 8 7 5]
 [0 7 8 ... 8 7 0]
 [8 1 3 ... 9 2 7]] (100, 12)


In [74]:
### 분할

x = [1,2,3,4,5,6,7,8]
x1, x2, x3 = np.split(x, [2,6])
print(x1, x2, x3)
### 인덱스를 [0,2) [2,6) [6, 마지막]으로 분류한 결과를 표시

[1 2] [3 4 5 6] [7 8]


In [86]:
### 행 / 열 분할

x = np.random.random((4,4))

x1, x2 = np.vsplit(x,[2])

print(x1)
print(x2)

y1, y2 = np.hsplit(x, [2])

print(y1)
print(y2)

[[0.89590156 0.26609952 0.43118378 0.32735898]
 [0.66622936 0.99921115 0.90337201 0.22882025]]
[[0.93102613 0.95966856 0.57699123 0.77115075]
 [0.95627128 0.21322431 0.30629184 0.7906168 ]]
[[0.89590156 0.26609952]
 [0.66622936 0.99921115]
 [0.93102613 0.95966856]
 [0.95627128 0.21322431]]
[[0.43118378 0.32735898]
 [0.90337201 0.22882025]
 [0.57699123 0.77115075]
 [0.30629184 0.7906168 ]]


In [95]:
### 병합

x = np.array([1,2])
y = np.array([3,4])
z = np.array([5,6])
xx = ([[1,2,3], [4,5,6]])
yy = ([[2,4,6], [8,7,6]])
zz = ([11,22,33])
ww = ([100], [200])

print(np.concatenate([x,y,z]))
print(np.concatenate([xx,yy]))
print(np.concatenate([xx,yy], axis=1))
print(np.vstack([zz,xx]))
print(np.hstack([ww,xx]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]
[[11 22 33]
 [ 1  2  3]
 [ 4  5  6]]
[[100   1   2   3]
 [200   4   5   6]]


## 1.1.2 연산

In [99]:
### 연산의 기본적인 개념은 브로드캐스팅(broadcasting)

x= np.array([1,2,3,4])
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x**3)
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [102]:
### 행렬의 연산

M = np.ones((3,3))
print(M)
M1  = M + 1
print(M1)

a = np.array([1,2,3])
M2 = M + a
print(M2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [104]:
### 행렬의 연산 2

a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [124]:
### 기초통계량의 산출
x = np.random.randint(10, size=(3,4))
print(x)

print(np.sum(x))
print(np.min(x, axis=1)) # 각 행의 최솟값들을 표현
print(np.max(x, axis=0)) # 각 열의 최댓값들을 표현
print(np.mean(x, axis=0))
print(np.std(x, axis=1)) # 각 행의 표준편차들을 표현

x_std = (x - np.mean(x, axis=0)) / np.std(x, axis=0) # 각 열별로 표준화한 행렬 생성
print(x_std)
print(np.sum(x_std, axis=0))

[[9 2 6 0]
 [4 9 5 8]
 [8 6 4 8]]
69
[0 4 4]
[9 9 6 8]
[7.         5.66666667 5.         5.33333333]
[3.49106001 2.06155281 1.6583124 ]
[[ 0.9258201  -1.27872403  1.22474487 -1.41421356]
 [-1.38873015  1.16247639  0.          0.70710678]
 [ 0.46291005  0.11624764 -1.22474487  0.70710678]]
[ 0.00000000e+00 -4.30211422e-16  0.00000000e+00  2.22044605e-16]


## 1.1.3 논리 인덱싱과 순서 정렬

In [11]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x>=5

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [13]:
np.sum(x>=5)

4

In [14]:
np.sum(x>=5, axis=1)

array([0, 4])

In [15]:
np.any(x>=100)

False

In [16]:
np.all(x<7, axis=0)

array([ True,  True, False, False])

In [17]:
np.all(x==100)

False

In [18]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
y = np.array([1,0,1,0])
x[y==1, :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [19]:
x[:,y==0]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [21]:
x = np.array([11,22,33,44,55,66,77,88,99])
ind1 = np.array([2,3,8])
ind2 = np.array([[2,1,3],[5,2,7]])

In [24]:
x1 = x[ind1]
x2 = x[ind2]
print(x1)
print(x2)

[33 44 99]
[[33 22 44]
 [66 33 88]]


In [26]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
y1 = np.array([1,2,2])
y2 = np.array([2,0,1])
x[y1, y2]

array([6, 8, 9])

In [28]:
x[y1[:, np.newaxis], y2]

array([[ 6,  4,  5],
       [10,  8,  9],
       [10,  8,  9]])

In [30]:
### 순서 정렬

x =  np.array([2,4,3,1,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [32]:
### 순서 정렬하여 위치 인덱스 순서대로 출력

ind = np.argsort(x)
print(ind)

[3 0 2 1 4]


# 1.2 판다스
- 넘파이는 동일한 자료타입 데이터만 허용되지만, 판다스는 다양한 자료 타입을 동시에 이용할 수 있다.
- 1차원 자료에 이용하는 클래스 Series와 2차원 자료에 사용하는 클래스 DataFrame이 있다.

In [49]:
import pandas as pd
X1 = pd.Series([0.1,0.2,0.3,0.4], index=['a','b','c','d'])
print(X1)

a    0.1
b    0.2
c    0.3
d    0.4
dtype: float64


In [51]:
X1.values

array([0.1, 0.2, 0.3, 0.4])

In [52]:
X1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [53]:
print(X1['a':'c'])
print(X1[0:3])

a    0.1
b    0.2
c    0.3
dtype: float64
a    0.1
b    0.2
c    0.3
dtype: float64


In [58]:
population1={'서울' : 9_700_000,
             '부산' : 4_500_000,
             '인천' : 4_000_000,
             '광주' : 2_000_000,
             '대구' : 2_500_000}
popu=pd.Series(population1)
print(popu)

서울    9700000
부산    4500000
인천    4000000
광주    2000000
대구    2500000
dtype: int64


In [60]:
X2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['a','b','c'], index=[1,2,3])
print(X2)

   a  b  c
1  1  2  3
2  4  5  6
3  7  8  9


In [61]:
print(X2.head(1))

   a  b  c
1  1  2  3


In [63]:
pd.DataFrame(popu, columns=['pop'])

pop
서울  9700000
부산  4500000
인천  4000000
광주  2000000
대구  2500000

In [65]:
ind1 = {'서울' : 95,
       '부산' : 80,
       '인천' : 85,
       '광주' : 75,
       '대구' : 80}
ind = pd.Series(ind1)
y = pd.DataFrame({'pop':popu, '자립도(%)':ind})
print(y)

        pop  자립도(%)
서울  9700000      95
부산  4500000      80
인천  4000000      85
광주  2000000      75
대구  2500000      80


In [66]:
print(y['자립도(%)'])

서울    95
부산    80
인천    85
광주    75
대구    80
Name: 자립도(%), dtype: int64


In [69]:
print(y['부산':'광주'])

        pop  자립도(%)
부산  4500000      80
인천  4000000      85
광주  2000000      75


In [72]:
W = pd.DataFrame(np.arange(12).reshape(3,4), columns=['a','b','c','d'])
print(W)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [78]:
print(W.loc[0:1,:])
print()
print(W.iloc[0:1,:])
print()
print(W.iloc[0:2]['c'])

   a  b  c  d
0  0  1  2  3
1  4  5  6  7

   a  b  c  d
0  0  1  2  3

0    2
1    6
Name: c, dtype: int32


In [83]:
D1 = pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
print(D1)
D2 = pd.DataFrame([[11,22,33],[44,55,66],[77,88,99]], columns=['a','b','c'])
print(D2)
print(D1+D2) # D1에 행 index 2가 없고, 열 index c가 없으므로 행렬의 덧셈연산은 NaN으로 표기
# 이러한 연산은 두 개의 자료 크기가 다르더라도 에러메세지 없이 실행된다는 점에서 매우 유용한 기능이다.
print(D1/D2)

   a  b
0  1  2
1  3  4
    a   b   c
0  11  22  33
1  44  55  66
2  77  88  99
      a     b   c
0  12.0  24.0 NaN
1  47.0  59.0 NaN
2   NaN   NaN NaN
          a         b   c
0  0.090909  0.090909 NaN
1  0.068182  0.072727 NaN
2       NaN       NaN NaN


In [87]:
### element-wise한 연산 말고 실제 선형대수적 행렬 연산을 하기 위해선 np.matmul()을 사용한다.
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
c = np.matmul(a,b)
print(c)
d = c.T #전치행렬
print(d)

[[22 28]
 [49 64]]
[[22 49]
 [28 64]]


## 1.2.1 결측 자료의 처리

In [92]:
N = pd.Series([1, np.nan, 'missing', None])
print(N.isnull())
print()
print(N.isnull().sum())

0    False
1     True
2    False
3     True
dtype: bool

2


In [95]:
print(N[N.notnull()])
print()
print(N.notnull().sum())
print()
N.fillna(0)

0          1
2    missing
dtype: object

2



0          1
1          0
2    missing
3          0
dtype: object

In [98]:
M = pd.DataFrame([[1,np.nan,2,np.nan],[4,5,6,np.nan],[np.nan,7,8,np.nan]], index=list('123'), columns=list('abcd'))
print(M)

     a    b  c   d
1  1.0  NaN  2 NaN
2  4.0  5.0  6 NaN
3  NaN  7.0  8 NaN


In [99]:
M.dropna(axis = 'columns', how = 'all')

a    b  c
1  1.0  NaN  2
2  4.0  5.0  6
3  NaN  7.0  8

In [100]:
M.dropna(axis = 'rows', thresh = 3)

a    b  c   d
2  4.0  5.0  6 NaN

In [101]:
M.fillna(method='bfill', axis = 1)

a    b    c   d
1  1.0  2.0  2.0 NaN
2  4.0  5.0  6.0 NaN
3  7.0  7.0  8.0 NaN

In [102]:
M.fillna(method = 'ffill', axis = 1)

a    b    c    d
1  1.0  1.0  2.0  2.0
2  4.0  5.0  6.0  6.0
3  NaN  7.0  8.0  8.0

## 1.2.2 논리적 인덱스

In [105]:
x = pd.DataFrame([[1,np.nan,2,np.nan],[3,4,5,np.nan],[np.nan,6,7,np.nan]], index=list('123'), columns=list('abcd'))
print(x)

     a    b  c   d
1  1.0  NaN  2 NaN
2  3.0  4.0  5 NaN
3  NaN  6.0  7 NaN


In [109]:
x.loc['2', 'd'] = 99
print(x)
print(x[pd.isnull(x['b'])])

     a    b  c     d
1  1.0  NaN  2   NaN
2  3.0  4.0  5  99.0
3  NaN  6.0  7   NaN
     a   b  c   d
1  1.0 NaN  2 NaN


In [110]:
### x의 각 행 중에서 하나라도 결측치가 있는 행을 찾아내서, 이 중 'b'열을 추출하라는 명령어
x[pd.isnull(x).any(axis=1)]['b']

1    NaN
3    6.0
Name: b, dtype: float64

In [111]:
### 동일한 결과
x.loc[pd.isnull(x).any(axis=1), 'b']

1    NaN
3    6.0
Name: b, dtype: float64

In [112]:
x[pd.isnull(x).any(axis=1), 'b'] # error발생

InvalidIndexError: (1     True
2    False
3     True
dtype: bool, 'b')

In [113]:
K = pd.DataFrame(np.arange(12).reshape(3,4), columns=list('abcd'))
print(K)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [114]:
K.loc[K['b']>4]['c']

1     6
2    10
Name: c, dtype: int32

In [115]:
### 동일한 결과
K.loc[K['b']>4,'c']

1     6
2    10
Name: c, dtype: int32

In [116]:
K.loc[K['b']>4, ['b','d']]

b   d
1  5   7
2  9  11

In [117]:
P=pd.DataFrame(np.arange(6).reshape(2,3), index=list('ab'), columns=list('123'))
print(P)

   1  2  3
a  0  1  2
b  3  4  5


In [118]:
P.stack()

a  1    0
   2    1
   3    2
b  1    3
   2    4
   3    5
dtype: int32

In [119]:
P.stack().unstack()

1  2  3
a  0  1  2
b  3  4  5

## 1.2.3 데이터 붙이기

In [121]:
Q1 = pd.DataFrame([[1,2,3],[4,5,6,]], columns=list('abc'))
Q2 = pd.DataFrame([[11,22,33],[44,55,66]], columns=list('bcd'))
print(Q1)
print(Q2)

   a  b  c
0  1  2  3
1  4  5  6
    b   c   d
0  11  22  33
1  44  55  66


In [122]:
### 데이터의 크기를 증가시키는(case를 증가시키는), 밑으로 붙이기
pd.concat([Q1, Q2])

a   b   c     d
0  1.0   2   3   NaN
1  4.0   5   6   NaN
0  NaN  11  22  33.0
1  NaN  44  55  66.0

In [123]:
### 밑으로 붙이기, index가 반복되지 않고 순서 있는 인덱스를 원한다면 ignore_index=True를 추가하면 된다.
pd.concat([Q1, Q2], ignore_index=True)

a   b   c     d
0  1.0   2   3   NaN
1  4.0   5   6   NaN
2  NaN  11  22  33.0
3  NaN  44  55  66.0

In [124]:
### 밑으로 붙이기, 공통으로 가지고 있는 열로만 구성된 자료를 원한다면 join='inner'를 사용하면 된다.
pd.concat([Q1, Q2], join='inner')

b   c
0   2   3
1   5   6
0  11  22
1  44  55

In [125]:
pd.concat([Q1,Q2], ignore_index=True, join='inner')

b   c
0   2   3
1   5   6
2  11  22
3  44  55

In [126]:
R1 = pd.DataFrame([[1,2,3],[4,5,6]], columns=list('abc'))
R2 = pd.DataFrame([[11,22],[33,44]], columns=list('de'))
print(R1)
print(R2)

   a  b  c
0  1  2  3
1  4  5  6
    d   e
0  11  22
1  33  44


In [128]:
### 데이터의 분석 변수를 추가할 때 많이 사용되는, 옆으로 붙이기
R3 = pd.concat([R1,R2], axis=1)
print(R3)

   a  b  c   d   e
0  1  2  3  11  22
1  4  5  6  33  44


In [129]:
S1 = pd.DataFrame([[1,'aa',3],[4,'bb',5]], columns=list('abc'))
S2 = pd.DataFrame([[11,'bb'],[22,'aa']], columns=list('db'))
print(S1)
print(S2)

   a   b  c
0  1  aa  3
1  4  bb  5
    d   b
0  11  bb
1  22  aa


In [131]:
### 공통의 정보를 가진 열 이름이 있을 경우 데이터 붙이기
S3 = pd.merge(S1,S2, on='b')
print(S3)

   a   b  c   d
0  1  aa  3  22
1  4  bb  5  11
